Repository Team-Ampersand/Dotori-Android, pull requests merged in 2023-09, with the labels that each got.

#3 🔀 :: (#2) add dependency for dus
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/ProjectProperties.kt
  buildSrc/src/main/java/Versions.kt
  data/build.gradle.kts
  di/build.gradle.kts
  domain/build.gradle.kts
  presentation/build.gradle.kts
  presentation/src/main/java/com/msg/presentation/view/.gitkeep
  presentation/src/main/java/com/msg/presentation/view/test.kt
  settings.gradle.kts
Labels: 0️⃣ Priority: Critical, ⚙ Type: Setting

#5 🔀 :: (#4) add cache and ktlint for ci
  .github/workflows/android.yml
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/ProjectProperties.kt
  buildSrc/src/main/java/Versions.kt
  data/build.gradle.kts
  di/build.gradle.kts
  domain/build.gradle.kts
  presentation/build.gradle.kts
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#7 🔀 :: (#6) publishing for login page
  buildSrc/src/main/java/Versions.kt
  presentation/src/main/java/com/msg/presentation/view/login/LoginScreen.kt
  presentation/src/main/java/com/msg/presentation/view/test.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#10 🔀 :: (#9) publishing for signup page
  app/src/main/AndroidManifest.xml
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/msg/presentation/view/signup/SignUpScreen.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#13 🔀 :: (#12) publishing for find password page
  presentation/src/main/java/com/msg/presentation/view/find_password/FindPasswordScreen.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#15 🔀 :: (#14) setting for di
  .github/workflows/android.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/dotori/DotoriApplication.kt
  app/src/main/java/com/msg/dotori/MainActivity.kt
  app/src/main/java/com/msg/dotori/module/NetworkModule.kt
  build.gradle.kts
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/ProjectProperties.kt
  buildSrc/src/main/java/Versions.kt
  data/build.gradle.kts
  di/src/main/java/com/msg/di/.gitkeep
  domain/build.gradle.kts
  presentation/build.gradle.kts
Labels: 1️⃣ Priority: High, ⚙ Type: Setting

#17 🔀 :: (#16) write auth remote logic
  app/build.gradle.kts
  app/src/main/java/com/msg/dotori/module/NetworkModule.kt
  data/src/main/java/com/msg/data/remote/dto/.gitkeep
  data/src/main/java/com/msg/data/remote/dto/auth/LoginRequest.kt
  data/src/main/java/com/msg/data/remote/dto/auth/LoginResponse.kt
  data/src/main/java/com/msg/data/remote/dto/auth/Role.kt
  data/src/main/java/com/msg/data/remote/network/.gitkeep
  data/src/main/java/com/msg/data/remote/network/AuthApi.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#19 🔀 :: (#18) write auth data logic
  app/src/main/java/com/msg/dotori/module/LocalDataSourceModule.kt
  app/src/main/java/com/msg/dotori/module/RemoteDataSourceModule.kt
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  data/build.gradle.kts
  data/src/main/java/com/msg/data/local/datasource/.gitkeep
  data/src/main/java/com/msg/data/local/datasource/LocalDataSource.kt
  data/src/main/java/com/msg/data/local/datasource/LocalDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/datasource/.gitkeep
  data/src/main/java/com/msg/data/remote/datasource/auth/AuthDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/auth/AuthDataSourceImpl.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#21 🔀 :: (#20) write exception handling logic
  data/build.gradle.kts
  data/src/main/java/com/msg/data/remote/datasource/auth/AuthDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/util/SafeApiCall.kt
  domain/src/main/java/com/msg/domain/exception/HttpException.kt
  domain/src/main/java/com/msg/domain/exception/NoInternetException.kt
  domain/src/main/java/com/msg/domain/exception/TokenExpiredException.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/msg/presentation/exception/ExceptionHandling.kt
Labels: 0️⃣ Priority: Critical, ✨ Type: Feature

#24 🔀 :: (#23) write auth domain logic
  app/build.gradle.kts
  app/src/main/java/com/msg/dotori/module/RepositoryModule.kt
  data/src/main/java/com/msg/data/remote/dto/auth/LoginRequest.kt
  data/src/main/java/com/msg/data/remote/dto/auth/LoginResponse.kt
  data/src/main/java/com/msg/data/remote/dto/auth/Role.kt
  data/src/main/java/com/msg/data/repository/.gitkeep
  data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/model/.gitkeep
  domain/src/main/java/com/msg/domain/model/auth/LoginRequestModel.kt
  domain/src/main/java/com/msg/domain/model/auth/LoginResponseModel.kt
  domain/src/main/java/com/msg/domain/model/auth/RoleModel.kt
  domain/src/main/java/com/msg/domain/repository/.gitkeep
  domain/src/main/java/com/msg/domain/repository/AuthRepository.kt
  domain/src/main/java/com/msg/domain/usecase/.gitkeep
  domain/src/main/java/com/msg/domain/usecase/auth/LoginUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/auth/SaveTokenUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/auth/TokenReissueUseCase.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#26 🔀 :: (#25) write auth presentation logic
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  data/src/main/java/com/msg/data/local/datasource/LocalDataSource.kt
  data/src/main/java/com/msg/data/local/datasource/LocalDataSourceImpl.kt
  data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/repository/AuthRepository.kt
  domain/src/main/java/com/msg/domain/usecase/auth/SaveTokenUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/msg/presentation/viewmodel/.gitkeep
  presentation/src/main/java/com/msg/presentation/viewmodel/LoginViewModel.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/util/Event.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#28 🔀 :: (#27) delete di module
  di/.gitignore
  di/build.gradle.kts
  di/consumer-rules.pro
  di/proguard-rules.pro
  di/src/androidTest/java/com/msg/di/ExampleInstrumentedTest.kt
  di/src/main/AndroidManifest.xml
  di/src/test/java/com/msg/di/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#30 🔀 :: (#29) write auth view model for other screen
  app/build.gradle.kts
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  data/build.gradle.kts
  domain/build.gradle.kts
  presentation/build.gradle.kts
  presentation/src/main/java/com/msg/presentation/view/login/LoginScreen.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#31 🔀 :: (#8) 자습 신청 화면 퍼블리싱
  buildSrc/src/main/java/ProjectProperties.kt
  buildSrc/src/main/java/Versions.kt
  presentation/src/main/java/com/msg/presentation/view/self_study/SelfStudyScreen.kt
  presentation/src/main/java/com/msg/presentation/view/self_study/component/BottomSheetContent.kt
  presentation/src/main/java/com/msg/presentation/view/self_study/component/EmptySelfStudyScreen.kt
  presentation/src/main/java/com/msg/presentation/view/self_study/component/TopBar.kt
  presentation/src/main/res/drawable/ic_empty_self_study_icon_dark.xml
  presentation/src/main/res/drawable/ic_empty_self_study_icon_light.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#35 🔀 :: (#33) write interceptor
  app/src/main/java/com/msg/dotori/module/NetworkModule.kt
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  data/build.gradle.kts
  data/src/main/java/com/msg/data/remote/util/AuthInterceptor.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#34 🔀 :: (#32) massage chair publishing
  presentation/src/main/java/com/msg/presentation/view/component/DotoriTopBar.kt
  presentation/src/main/java/com/msg/presentation/view/massage_chair/MassageChairScreen.kt
  presentation/src/main/java/com/msg/presentation/view/massage_chair/component/EmptyMassageChairScreen.kt
  presentation/src/main/java/com/msg/presentation/view/massage_chair/component/MassageChairTopBar.kt
  presentation/src/main/java/com/msg/presentation/view/self_study/SelfStudyScreen.kt
  presentation/src/main/java/com/msg/presentation/view/self_study/component/SelfStudyTopBar.kt
  presentation/src/main/res/drawable/ic_empty_massage_chair_icon_dark.xml
  presentation/src/main/res/drawable/ic_empty_massage_chair_icon_light.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#22 🔀 :: (#11) music page publishing
  presentation/src/main/java/com/msg/presentation/view/music/BottomSheetContent.kt
  presentation/src/main/java/com/msg/presentation/view/music/BottomSheetType.kt
  presentation/src/main/java/com/msg/presentation/view/music/DotoriTopBar.kt
  presentation/src/main/java/com/msg/presentation/view/music/MusicDialogContent.kt
  presentation/src/main/java/com/msg/presentation/view/music/MusicHeader.kt
  presentation/src/main/java/com/msg/presentation/view/music/MusicScreen.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#39 🔀 :: (#38) write music remote logic
  app/src/main/java/com/msg/dotori/module/NetworkModule.kt
  data/src/main/java/com/msg/data/remote/dto/music/MusicRequest.kt
  data/src/main/java/com/msg/data/remote/dto/music/MusicResponse.kt
  data/src/main/java/com/msg/data/remote/network/MusicApi.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#41 🔀 :: (#40) write music data logic
  app/src/main/java/com/msg/dotori/module/RemoteDataSourceModule.kt
  data/src/main/java/com/msg/data/remote/datasource/music/MusicDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/music/MusicDataSourceImpl.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#43 🔀 :: (#42) write music domain logic
  app/src/main/java/com/msg/dotori/module/RepositoryModule.kt
  data/src/main/java/com/msg/data/remote/dto/music/MusicRequest.kt
  data/src/main/java/com/msg/data/remote/dto/music/MusicResponse.kt
  data/src/main/java/com/msg/data/repository/MusicRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/model/music/request/MusicRequestModel.kt
  domain/src/main/java/com/msg/domain/model/music/response/MusicResponseModel.kt
  domain/src/main/java/com/msg/domain/repository/MusicRepository.kt
  domain/src/main/java/com/msg/domain/usecase/music/DeleteMusicUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/music/GetMusicsUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/music/RequestMusicUseCase.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#45 🔀 :: (#44) write music viewmodel logic
  presentation/src/main/java/com/msg/presentation/viewmodel/MusicViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#46 🔀 :: (#37) publishing for student info page
  buildSrc/src/main/java/Versions.kt
  presentation/src/main/java/com/msg/presentation/view/login/LoginScreen.kt
  presentation/src/main/java/com/msg/presentation/view/student_info/StudentInfoScreen.kt
  presentation/src/main/java/com/msg/presentation/view/student_info/component/DotoriHamburgerTopBar.kt
  presentation/src/main/java/com/msg/presentation/view/student_info/component/StudentInfoBottomSheetContent.kt
  presentation/src/main/java/com/msg/presentation/view/student_info/component/StudentInfoBottomSheetType.kt
  presentation/src/main/java/com/msg/presentation/view/student_info/component/StudentInfoDialogContent.kt
  presentation/src/main/java/com/msg/presentation/view/student_info/component/StudentInfoHeader.kt
  presentation/src/main/java/com/msg/presentation/view/student_info/component/StudentInfoSegmentButton.kt
  presentation/src/main/java/com/msg/presentation/view/student_info/component/StudentInfoTextField.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#49 🔀 :: (#47) write student info remote logic
  app/src/main/java/com/msg/dotori/module/NetworkModule.kt
  data/src/main/java/com/msg/data/remote/dto/student_info/SearchStudentInfoResponse.kt
  data/src/main/java/com/msg/data/remote/dto/student_info/StudentInfoRequest.kt
  data/src/main/java/com/msg/data/remote/dto/student_info/StudentInfoResponse.kt
  data/src/main/java/com/msg/data/remote/network/SelfStudyApi.kt
  data/src/main/java/com/msg/data/remote/network/StudentInfoApi.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#51 🔀 :: (#50) write student info data logic
  app/src/main/java/com/msg/dotori/module/RemoteDataSourceModule.kt
  data/src/main/java/com/msg/data/remote/datasource/self_study/SelfStudyDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/self_study/SelfStudyDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/datasource/student_info/StudentInfoDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/student_info/StudentInfoDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/dto/student_info/SelfStudyStatus.kt
  data/src/main/java/com/msg/data/remote/dto/student_info/StudentInfoResponse.kt
  data/src/main/java/com/msg/data/remote/network/StudentInfoApi.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#52 🔀 :: (#48) self study api logic
  data/src/main/java/com/msg/data/remote/dto/self_study/SelfStudyInfoResponse.kt
  data/src/main/java/com/msg/data/remote/dto/self_study/SelfStudyListResponse.kt
  data/src/main/java/com/msg/data/remote/network/SelfStudyApi.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#55 🔀 :: (#54) write student info domain logic
  app/src/main/java/com/msg/dotori/module/RepositoryModule.kt
  data/src/main/java/com/msg/data/remote/dto/auth/Role.kt
  data/src/main/java/com/msg/data/remote/dto/student_info/SearchStudentInfoResponse.kt
  data/src/main/java/com/msg/data/remote/dto/student_info/SelfStudyStatus.kt
  data/src/main/java/com/msg/data/remote/dto/student_info/StudentInfoRequest.kt
  data/src/main/java/com/msg/data/remote/dto/student_info/StudentInfoResponse.kt
  data/src/main/java/com/msg/data/repository/SelfStudyRepositoryImpl.kt
  data/src/main/java/com/msg/data/repository/StudentInfoRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/model/student_info/SearchStudentInfoResponseModel.kt
  domain/src/main/java/com/msg/domain/model/student_info/SelfStudyStatusModel.kt
  domain/src/main/java/com/msg/domain/model/student_info/StudentInfoRequestModel.kt
  domain/src/main/java/com/msg/domain/model/student_info/StudentInfoResponseModel.kt
  domain/src/main/java/com/msg/domain/repository/SelfStudyRepository.kt
  domain/src/main/java/com/msg/domain/repository/StudentInfoRepository.kt
  domain/src/main/java/com/msg/domain/usecase/self_study/BanCancelSelfStudyUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/self_study/BanSelfStudyUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/student_info/GetAllStudentInfoUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/student_info/GetSearchStudentInfoUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/student_info/ModifyStudentInfoUseCase.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#58 🔀 :: (#56) write student info presentation logic
  domain/src/main/java/com/msg/domain/usecase/student_info/GetSearchStudentInfoUseCase.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/StudentInfoViewModel.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#59 🔀 :: (#53) self study data
  data/src/main/java/com/msg/data/remote/datasource/self_study/SelfStudyDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/self_study/SelfStudyDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/network/SelfStudyApi.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#62 🔀 :: (#61) self study domain
  data/src/main/java/com/msg/data/remote/dto/self_study/SelfStudyInfoResponse.kt
  data/src/main/java/com/msg/data/remote/dto/self_study/SelfStudyListResponse.kt
  data/src/main/java/com/msg/data/repository/SelfStudyRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/model/self_study/SelfStudyInfoResponseModel.kt
  domain/src/main/java/com/msg/domain/model/self_study/SelfStudyListResponseModel.kt
  domain/src/main/java/com/msg/domain/repository/SelfStudyRepository.kt
  domain/src/main/java/com/msg/domain/usecase/self_study/CancelSelfStudyUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/self_study/ChangeSelfStudyLimitUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/self_study/CheckSelfStudyUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/self_study/GetSelfStudyInfoUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/self_study/GetSelfStudyListUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/self_study/SearchSelfStudyStudentUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/self_study/SelfStudyUseCase.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#63 🔀 :: (#57) empty music page publishing
  presentation/src/main/java/com/msg/presentation/view/music/MusicScreen.kt
  presentation/src/main/res/drawable/ic_empty_music_icon_dark.xml
  presentation/src/main/res/drawable/ic_empty_music_icon_light.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#65 🔀 :: (#60) write student info view model for other screen
  presentation/src/main/java/com/msg/presentation/view/student_info/StudentInfoScreen.kt
  presentation/src/main/java/com/msg/presentation/view/student_info/component/StudentInfoBottomSheetContent.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#71 🔀 :: (#70) write navigate logic
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/dotori/DotoriNavHost.kt
  app/src/main/java/com/msg/dotori/MainActivity.kt
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/msg/presentation/view/find_password/navigation/FindPasswordNavigation.kt
  presentation/src/main/java/com/msg/presentation/view/login/navigation/LoginNavigation.kt
  presentation/src/main/java/com/msg/presentation/view/massage_chair/navigation/MassageChairNavigation.kt
  presentation/src/main/java/com/msg/presentation/view/music/MusicScreen.kt
  presentation/src/main/java/com/msg/presentation/view/music/component/BottomSheetContent.kt
  presentation/src/main/java/com/msg/presentation/view/music/component/BottomSheetType.kt
  presentation/src/main/java/com/msg/presentation/view/music/component/DotoriTopBar.kt
  presentation/src/main/java/com/msg/presentation/view/music/component/MusicDialogContent.kt
  presentation/src/main/java/com/msg/presentation/view/music/component/MusicHeader.kt
  presentation/src/main/java/com/msg/presentation/view/music/navigation/MusicNavigation.kt
  presentation/src/main/java/com/msg/presentation/view/self_study/navigation/SelfStudyNavigation.kt
  presentation/src/main/java/com/msg/presentation/view/signup/navigation/SignUpNavigation.kt
  presentation/src/main/java/com/msg/presentation/view/student_info/navigation/StudentInfoNavigation.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#69 🔀 :: (#64) connet music viewmodel to screen
  presentation/src/main/java/com/msg/presentation/view/music/MusicScreen.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#74 🔀 :: (#73) write dotori theme
  app/build.gradle.kts
  app/src/main/java/com/msg/dotori/MainActivity.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#75 🔀 :: (#72) write theme switch logic
  presentation/src/main/java/com/msg/presentation/view/massage_chair/MassageChairScreen.kt
  presentation/src/main/java/com/msg/presentation/view/music/MusicScreen.kt
  presentation/src/main/java/com/msg/presentation/view/music/component/DotoriTopBar.kt
  presentation/src/main/java/com/msg/presentation/view/self_study/SelfStudyScreen.kt
  presentation/src/main/java/com/msg/presentation/view/student_info/StudentInfoScreen.kt
  presentation/src/main/java/com/msg/presentation/view/util/UpdateDotoriTheme.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#78 🔀 :: (#66) self study view model
  data/src/main/java/com/msg/data/remote/datasource/self_study/SelfStudyDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/self_study/SelfStudyDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/network/SelfStudyApi.kt
  data/src/main/java/com/msg/data/repository/SelfStudyRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/java/com/msg/domain/repository/SelfStudyRepository.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/msg/presentation/viewmodel/SelfStudyViewModel.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/util/Event.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#81 🔀 :: (#80) write music click event logic
  presentation/src/main/java/com/msg/presentation/view/music/MusicScreen.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#83 🔀 :: (#79) write youtube music remote logic
  data/build.gradle.kts
  data/src/main/java/com/msg/data/remote/datasource/music/MusicDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/music/MusicDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/dto/music/request/MusicRequest.kt
  data/src/main/java/com/msg/data/remote/dto/music/response/MusicResponse.kt
  data/src/main/java/com/msg/data/remote/dto/music/response/YoutubeResponse.kt
  data/src/main/java/com/msg/data/remote/network/MusicApi.kt
  data/src/main/java/com/msg/data/repository/MusicRepositoryImpl.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#77 🔀 :: (#76) write role save logic
  data/src/main/java/com/msg/data/local/datasource/LocalDataSource.kt
  data/src/main/java/com/msg/data/local/datasource/LocalDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/util/AuthInterceptor.kt
  data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/repository/AuthRepository.kt
  domain/src/main/java/com/msg/domain/usecase/auth/SaveRoleUseCase.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/LoginViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#85 🔀 :: (#84) write youtube music data logic
  data/src/main/java/com/msg/data/remote/datasource/music/MusicDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/music/MusicDataSourceImpl.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#87 🔀 :: (#82) self study ui logic
  presentation/src/main/java/com/msg/presentation/view/self_study/SelfStudyScreen.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#88 🔀 :: (#86) write youtube music domain logic
  data/src/main/java/com/msg/data/remote/dto/music/response/YoutubeResponse.kt
  data/src/main/java/com/msg/data/repository/MusicRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/model/music/response/YoutubeResponseModel.kt
  domain/src/main/java/com/msg/domain/repository/MusicRepository.kt
  domain/src/main/java/com/msg/domain/usecase/music/GetYoutubeMusicUseCase.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#91 🔀 :: (#89) write youtube music viewmodel logic
  domain/src/main/java/com/msg/domain/model/music/response/MusicModel.kt
  presentation/src/main/java/com/msg/presentation/view/music/MusicScreen.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/MusicViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#93 🔀 :: (#92) connect youtube music logic to screen
  presentation/src/main/java/com/msg/presentation/view/music/MusicScreen.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#96 🔀 :: (#95) write local role logic
  data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/repository/AuthRepository.kt
  domain/src/main/java/com/msg/domain/usecase/auth/GetRoleUseCase.kt
  presentation/src/main/java/com/msg/presentation/view/music/MusicScreen.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/MusicViewModel.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/util/GetRolePath.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#98 🔀 :: (#90) massage chair api
  app/src/main/java/com/msg/dotori/module/NetworkModule.kt
  data/src/main/java/com/msg/data/remote/dto/massage/MassageInfoResponse.kt
  data/src/main/java/com/msg/data/remote/dto/massage/MassageListResponse.kt
  data/src/main/java/com/msg/data/remote/network/MassageApi.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#100 🔀 :: (#99) massage chair data
  app/src/main/java/com/msg/dotori/module/RemoteDataSourceModule.kt
  data/src/main/java/com/msg/data/remote/datasource/massage/MassageDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/massage/MassageDataSourceImpl.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#102 🔀 :: (#101) massage chair domain
  app/src/main/java/com/msg/dotori/module/RepositoryModule.kt
  data/src/main/java/com/msg/data/remote/datasource/massage/MassageDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/massage/MassageDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/dto/massage/MassageInfoResponse.kt
  data/src/main/java/com/msg/data/remote/dto/massage/MassageListResponse.kt
  data/src/main/java/com/msg/data/repository/MassageRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/model/massage/MassageInfoResponseModel.kt
  domain/src/main/java/com/msg/domain/model/massage/MassageListResponseModel.kt
  domain/src/main/java/com/msg/domain/repository/MassageRepository.kt
  domain/src/main/java/com/msg/domain/usecase/massage/CancelMassageUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/massage/ChangeMassageLimitUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/massage/GetMassageInfoUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/massage/GetMassageRankUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/massage/RequestMassageUseCase.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#104 🔀 :: (#103) massage chair view model
  data/src/main/java/com/msg/data/remote/datasource/massage/MassageDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/massage/MassageDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/network/MassageApi.kt
  data/src/main/java/com/msg/data/repository/MassageRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/repository/MassageRepository.kt
  domain/src/main/java/com/msg/domain/usecase/massage/GetMassageInfoUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/massage/GetMassageRankUseCase.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/MassageViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#106 🔀 :: (#105) massage chair ui
  presentation/src/main/java/com/msg/presentation/view/massage_chair/MassageChairScreen.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/MassageViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#108 🔀 :: (#107) self study get role
  buildSrc/src/main/java/Versions.kt
  presentation/src/main/java/com/msg/presentation/view/self_study/SelfStudyScreen.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/MassageViewModel.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/SelfStudyViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#109 🔀 :: (#97) notice page publishing
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/msg/presentation/view/notice/NoticeDetailScreen.kt
  presentation/src/main/java/com/msg/presentation/view/notice/NoticeEditScreen.kt
  presentation/src/main/java/com/msg/presentation/view/notice/NoticeScreen.kt
  presentation/src/main/java/com/msg/presentation/view/notice/component/MonthDivider.kt
  presentation/src/main/java/com/msg/presentation/view/notice/component/NoticeDetailHeader.kt
  presentation/src/main/java/com/msg/presentation/view/notice/component/NoticeDetailTitle.kt
  presentation/src/main/java/com/msg/presentation/view/notice/component/NoticeDialogContent.kt
  presentation/src/main/java/com/msg/presentation/view/notice/component/NoticeEditHeader.kt
  presentation/src/main/java/com/msg/presentation/view/notice/component/NoticeEditImage.kt
  presentation/src/main/java/com/msg/presentation/view/notice/component/NoticeHeader.kt
  presentation/src/main/res/drawable/ic_add_image.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#111 🔀 :: (#110) write notice remote logic
  app/src/main/java/com/msg/dotori/module/NetworkModule.kt
  data/src/main/java/com/msg/data/remote/dto/notice/request/NoticeRequest.kt
  data/src/main/java/com/msg/data/remote/dto/notice/response/NoticeResponse.kt
  data/src/main/java/com/msg/data/remote/network/NoticeApi.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#113 🔀 :: (#112) write notice data logic
  app/src/main/java/com/msg/dotori/module/RemoteDataSourceModule.kt
  data/src/main/java/com/msg/data/remote/datasource/notice/NoticeDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/notice/NoticeDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/network/NoticeApi.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#115 🔀 :: (#114) write notice domain logic
  app/src/main/java/com/msg/dotori/module/RepositoryModule.kt
  data/src/main/java/com/msg/data/remote/dto/notice/request/NoticeRequest.kt
  data/src/main/java/com/msg/data/remote/dto/notice/response/NoticeResponse.kt
  data/src/main/java/com/msg/data/repository/NoticeRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/model/notice/request/NoticeRequestModel.kt
  domain/src/main/java/com/msg/domain/model/notice/response/NoticeResponseModel.kt
  domain/src/main/java/com/msg/domain/repository/NoticeRepository.kt
  domain/src/main/java/com/msg/domain/usecase/notice/DeleteNoticeByIdListUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/notice/DeleteNoticeByIdUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/notice/GetAllNoticeUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/notice/GetNoticeDetailUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/notice/ModifyNoticeUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/notice/WriteNoticeUseCase.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#117 🔀 :: (#116) write notice viewmodel logic
  data/src/main/java/com/msg/data/remote/datasource/notice/NoticeDataSource.kt
  data/src/main/java/com/msg/data/remote/dto/notice/response/NoticeDetailResponse.kt
  data/src/main/java/com/msg/data/remote/network/NoticeApi.kt
  data/src/main/java/com/msg/data/repository/NoticeRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/model/notice/response/NoticeDetailResponseModel.kt
  domain/src/main/java/com/msg/domain/repository/NoticeRepository.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/notice/NoticeDetailViewModel.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/notice/NoticeEditViewModel.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/notice/NoticeViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#119 🔀 :: (#118) connect notice logic to screen
  presentation/src/main/java/com/msg/presentation/view/notice/NoticeDetailScreen.kt
  presentation/src/main/java/com/msg/presentation/view/notice/NoticeEditScreen.kt
  presentation/src/main/java/com/msg/presentation/view/notice/NoticeScreen.kt
  presentation/src/main/java/com/msg/presentation/view/notice/component/NoticeEditImage.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#123 🔀 :: (#122) write rule violation remote logic
  app/src/main/java/com/msg/dotori/module/NetworkModule.kt
  data/src/main/java/com/msg/data/remote/dto/rule_violation/requset/RuleViolationRequest.kt
  data/src/main/java/com/msg/data/remote/dto/rule_violation/response/RuleViolationResponse.kt
  data/src/main/java/com/msg/data/remote/dto/rule_violation/response/SearchRuleViolationResponse.kt
  data/src/main/java/com/msg/data/remote/network/RuleViolationApi.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#125 🔀 :: (#124) write rule violation data logic
  app/src/main/java/com/msg/dotori/module/RemoteDataSourceModule.kt
  data/src/main/java/com/msg/data/remote/datasource/rule_violation/RuleViolationDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/rule_violation/RuleViolationDataSourceImpl.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#127 🔀 :: (#126) write rule violation domain logic
  app/src/main/java/com/msg/dotori/module/RepositoryModule.kt
  data/src/main/java/com/msg/data/remote/dto/rule_violation/requset/RuleViolationRequest.kt
  data/src/main/java/com/msg/data/remote/dto/rule_violation/response/RuleViolationResponse.kt
  data/src/main/java/com/msg/data/remote/dto/rule_violation/response/SearchRuleViolationResponse.kt
  data/src/main/java/com/msg/data/repository/RuleViolationRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/model/rule_violation/request/RuleViolationRequestModel.kt
  domain/src/main/java/com/msg/domain/model/rule_violation/response/RuleViolationResponseModel.kt
  domain/src/main/java/com/msg/domain/model/rule_violation/response/SearchRuleViolationResponseModel.kt
  domain/src/main/java/com/msg/domain/repository/RuleViolationRepository.kt
  domain/src/main/java/com/msg/domain/usecase/rule_violation/DeleteRuleViolationUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/rule_violation/GetDetailRuleViolationUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/rule_violation/GetSelfRuleViolationUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/rule_violation/PostRuleViolationUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/rule_violation/SearchRuleViolationUseCase.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#121 🔀 :: (#94) rule violation page publishing
  presentation/src/main/java/com/msg/presentation/view/rule_violation/RuleViolationScreen.kt
  presentation/src/main/java/com/msg/presentation/view/rule_violation/component/RuleViolationDialogContent.kt
  presentation/src/main/java/com/msg/presentation/view/rule_violation/component/RuleViolationDialogType.kt
  presentation/src/main/java/com/msg/presentation/view/rule_violation/component/RuleViolationHeader.kt
  presentation/src/main/java/com/msg/presentation/view/rule_violation/component/RuleViolationListItem.kt
  presentation/src/main/java/com/msg/presentation/view/rule_violation/component/RuleViolationTextItem.kt
  presentation/src/main/java/com/msg/presentation/view/rule_violation/component/RuleViolationToggle.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#129 🔀 :: (#128) write rule violation viewmodel logic
  presentation/src/main/java/com/msg/presentation/viewmodel/LoginViewModel.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/RuleViolationViewModel.kt
Labels: 1️⃣ Priority: High, 📬 Type: API
