Repository Team-Ampersand/Dotori-Android, pull requests merged in 2023-10, with the labels that each got.

#132 🔀 :: (#131) add get student info logic for rule violation viewmodel
  presentation/src/main/java/com/msg/presentation/viewmodel/RuleViolationViewModel.kt
Labels: 0️⃣ Priority: Critical, 📬 Type: API

#130 🔀 :: (#120) write notice navigation logic
  app/src/main/java/com/msg/dotori/DotoriNavHost.kt
  presentation/src/main/java/com/msg/presentation/view/notice/NoticeDetailScreen.kt
  presentation/src/main/java/com/msg/presentation/view/notice/NoticeEditScreen.kt
  presentation/src/main/java/com/msg/presentation/view/notice/NoticeScreen.kt
  presentation/src/main/java/com/msg/presentation/view/notice/navigation/NoticeDetailNavigation.kt
  presentation/src/main/java/com/msg/presentation/view/notice/navigation/NoticeEditNavigation.kt
  presentation/src/main/java/com/msg/presentation/view/notice/navigation/NoticeNavigation.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#134 🔀 :: (#133) connect rule violation screen for viewmodel
  presentation/src/main/java/com/msg/presentation/view/rule_violation/RuleViolationScreen.kt
  presentation/src/main/java/com/msg/presentation/view/rule_violation/component/RuleViolationDialogContent.kt
  presentation/src/main/java/com/msg/presentation/view/rule_violation/component/RuleViolationTextItem.kt
Labels: 0️⃣ Priority: Critical, 📬 Type: API

#136 🔀 :: (#135) publishing remaining pages
  presentation/src/main/java/com/msg/presentation/view/home/HomeScreen.kt
  presentation/src/main/java/com/msg/presentation/view/rule_violation/RuleViolationWebScreen.kt
Labels: 0️⃣ Priority: Critical, 🎨 Type: Publishing
