Repository Team-Ampersand/Dotori-Android, pull requests merged in 2023-11, with the labels that each got.

#138 🔀 : ::(#137) bottom navigation edit
  app/src/main/java/com/msg/dotori/DotoriNavHost.kt
  app/src/main/java/com/msg/dotori/MainActivity.kt
  presentation/src/main/java/com/msg/presentation/view/home/navigation/HomeNavigation.kt
Labels: 0️⃣ Priority: Critical, ✨ Type: Feature

#142 🔀 :: (#140) login page publishing
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/msg/presentation/view/login/GAuthLoginScreen.kt
  presentation/src/main/res/values/string.xml
Labels: ✨ Type: Feature

#141 🔀 :: (#141) add android cd
  .github/workflows/android_cd.yml
Labels: ⚙ Type: Setting

#145 🔀 :: (#141) gauth login remote logic
  app/src/main/java/com/msg/dotori/module/NetworkModule.kt
  data/src/main/java/com/msg/data/remote/dto/auth/GAuthLoginRequest.kt
  data/src/main/java/com/msg/data/remote/dto/auth/GAuthLoginResponse.kt
  data/src/main/java/com/msg/data/remote/network/GAuthApi.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#147 🔀 :: (#142) gauth login data logic
  app/src/main/java/com/msg/dotori/module/RemoteDataSourceModule.kt
  data/src/main/java/com/msg/data/remote/datasource/auth/GAuthDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/auth/GAuthDataSourceImpl.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#149 🔀 :: (#143) gauth login domain logic
  app/src/main/java/com/msg/dotori/module/RepositoryModule.kt
  data/src/main/java/com/msg/data/remote/dto/auth/GAuthLoginResponse.kt
  data/src/main/java/com/msg/data/repository/GAuthRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/model/auth/GAuthLoginRequestModel.kt
  domain/src/main/java/com/msg/domain/model/auth/GAuthLoginResponseModel.kt
  domain/src/main/java/com/msg/domain/repository/GAuthRepository.kt
  domain/src/main/java/com/msg/domain/usecase/auth/GAuthLoginUseCase.kt
Labels: 1️⃣ Priority: High, 📬 Type: API
