Repository Team-Ampersand/Dotori-Android, pull requests merged in 2024-02, with the labels that each got.

#157 🔀 :: (#156) write the logic sign up
  app/src/main/java/com/msg/dotori/DotoriNavHost.kt
  app/src/main/java/com/msg/dotori/module/NetworkModule.kt
  app/src/main/java/com/msg/dotori/module/RemoteDataSourceModule.kt
  app/src/main/java/com/msg/dotori/module/RepositoryModule.kt
  data/src/main/java/com/msg/data/remote/datasource/auth/AuthDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/auth/AuthDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/datasource/email/EmailDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/email/EmailDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/dto/auth/Gender.kt
  data/src/main/java/com/msg/data/remote/dto/auth/SignUpRequest.kt
  data/src/main/java/com/msg/data/remote/dto/email/EmailVerifyRequest.kt
  data/src/main/java/com/msg/data/remote/dto/email/SendEmailRequest.kt
  data/src/main/java/com/msg/data/remote/network/AuthApi.kt
  data/src/main/java/com/msg/data/remote/network/EmailApi.kt
  data/src/main/java/com/msg/data/remote/util/AuthInterceptor.kt
  data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/msg/data/repository/EmailRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/model/auth/GenderModel.kt
  domain/src/main/java/com/msg/domain/model/auth/SignUpRequestModel.kt
  domain/src/main/java/com/msg/domain/model/email/EmailVerifyRequestModel.kt
  domain/src/main/java/com/msg/domain/model/email/SendEmailRequestModel.kt
  domain/src/main/java/com/msg/domain/repository/AuthRepository.kt
  domain/src/main/java/com/msg/domain/repository/EmailRepository.kt
  domain/src/main/java/com/msg/domain/usecase/auth/SignUpUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/email/EmailVerifyUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/email/SendEmailUseCase.kt
  presentation/src/main/java/com/msg/presentation/view/component/dotoriClickable.kt
  presentation/src/main/java/com/msg/presentation/view/login/LoginScreen.kt
  presentation/src/main/java/com/msg/presentation/view/signup/AuthenticationScreen.kt
  presentation/src/main/java/com/msg/presentation/view/signup/PasswordScreen.kt
  presentation/src/main/java/com/msg/presentation/view/signup/SignUpScreen.kt
  presentation/src/main/java/com/msg/presentation/view/signup/navigation/SignUpNavigation.kt
  presentation/src/main/java/com/msg/presentation/view/util/toGenderText.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/SignUpViewModel.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/util/SignUpViewModelProvider.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#159 🔀 :: (#158) create regular expression
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/msg/presentation/view/login/LoginScreen.kt
  presentation/src/main/java/com/msg/presentation/view/signup/AuthenticationScreen.kt
  presentation/src/main/java/com/msg/presentation/view/signup/PasswordScreen.kt
  presentation/src/main/java/com/msg/presentation/view/util/isStrongEmail.kt
  presentation/src/main/java/com/msg/presentation/view/util/isStrongPassword.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/LoginViewModel.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/SignUpViewModel.kt
Labels: 0️⃣ Priority: Critical, 🪛 Type: Performance

#161 🔀 :: (#151) publishing home
  presentation/src/main/java/com/msg/presentation/view/home/HomeScreen.kt
  presentation/src/main/java/com/msg/presentation/view/home/component/Cafeteria.kt
  presentation/src/main/java/com/msg/presentation/view/home/component/CalendarHeader.kt
  presentation/src/main/java/com/msg/presentation/view/home/component/DotoriMainTopBar.kt
  presentation/src/main/res/drawable/ic_left_icon.xml
  presentation/src/main/res/drawable/ic_right_icon.xml
  presentation/src/main/res/values/string.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#164 🔀 :: (#163) write the logic find password
  app/src/main/java/com/msg/dotori/DotoriNavHost.kt
  data/src/main/java/com/msg/data/remote/datasource/auth/AuthDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/auth/AuthDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/datasource/email/EmailDataSource.kt
  data/src/main/java/com/msg/data/remote/datasource/email/EmailDataSourceImpl.kt
  data/src/main/java/com/msg/data/remote/dto/auth/ChangePasswordRequest.kt
  data/src/main/java/com/msg/data/remote/network/AuthApi.kt
  data/src/main/java/com/msg/data/remote/network/EmailApi.kt
  data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/msg/data/repository/EmailRepositoryImpl.kt
  domain/src/main/java/com/msg/domain/model/auth/ChangePasswordRequestModel.kt
  domain/src/main/java/com/msg/domain/repository/AuthRepository.kt
  domain/src/main/java/com/msg/domain/repository/EmailRepository.kt
  domain/src/main/java/com/msg/domain/usecase/auth/ChangePasswordUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/email/SendPasswordEmailUseCase.kt
  domain/src/main/java/com/msg/domain/usecase/email/SendSignUpEmailUseCase.kt
  presentation/src/main/java/com/msg/presentation/view/find_password/FindPasswordScreen.kt
  presentation/src/main/java/com/msg/presentation/view/find_password/PasswordAuthenticationScreen.kt
  presentation/src/main/java/com/msg/presentation/view/find_password/navigation/FindPasswordNavigation.kt
  presentation/src/main/java/com/msg/presentation/view/signup/AuthenticationScreen.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/FindPasswordViewModel.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/SignUpViewModel.kt
  presentation/src/main/java/com/msg/presentation/viewmodel/util/FindPasswordViewModelProvider.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature
